config/routes.rb
Stylejonction::Application.routes.draw do
  
  require 'subdomain'
  devise_for :users
  
  match "/users" => "users#index"
  
  constraints(Subdomain) do
    match '/' => 'portfolios#edit_layout'

    resource :portfolio, :except => [:destroy, :new] do
      member do
        get 'edit_layout'
        get 'edit_font'
        put 'publish'
      end
      resources :projects, :except => [:index]  do
        member do
          post 'invite'
        end
      end
    end
  end
  
  resources :custom_backgrounds, :only => [:edit, :update, :create] do
     member do
       post 'upload'
       get 'remove_upload'
     end
  end
  resources :predefined_backgrounds, :only => [:show]
  resources :patterns, :only => [:show]
  resources :invitations, :only => [:show]
  resources :fonts, :only => [:show]
  resources :images do
    member do
      post 'upload'
      match 'crop'
      match 'remove_upload'
    end
  end
  resources :text_blocks, :except => [:index]
  resources :galleries, :except => [:index] do 
    resources :videos
    resources :photos do 
      collection do
        post "upload" 
      end
    end
  end
  resources :document_blocks, :except => [:index] do 
    resources :documents
  end
  
  
  # This duplicates upload_image but doesn't need id
  match "/images/upload" => 'images#upload', :via => "post"

  #match "portfolio/:id" => "portfolios#show"
  match '#/:page' => 'pages#:page', :as => :page
  root :to => "pages#index"
end

app/models/document_block.rb
class DocumentBlock < Element
  has_many :documents , :dependent => :destroy, :order  => 'weight'

  belongs_to :project 
  
  validates_presence_of :title, :project_id
end

app/controllers/document_blocks_controller.rb
class DocumentBlocksController < ApplicationController
  

  # GET /document_blocks/1
  # GET /document_blocks/1.json
  def show
    @document_block = DocumentBlock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document_block }
    end
  end

  # GET /document_blocks/new
  # GET /document_blocks/new.json
  def new
    @document_block = DocumentBlock.new

    respond_to do |format|
      format.html {redirect_to edit_portfolio_project_path(params[:project_id])+"?new_document_block=1"}
      format.json { render json: @document_block }
    end
  end

  # GET /document_blocks/1/edit
  def edit
    @document_block = DocumentBlock.find(params[:id])
    redirect_to get_redirect_path
  end

  # POST /document_blocks
  # POST /document_blocks.json
  def create
    @document_block = DocumentBlock.new(params[:document_block])

    respond_to do |format|
      if @document_block.save
        format.html { redirect_to get_redirect_path, notice: 'Document block was successfully created.' }
        format.json { render json: @document_block, status: :created, location: @document_block }
      else
        flash[:error] = "Document block cannot be created due to validation errors"
        format.html { redirect_to edit_portfolio_project_path(@document_block.project_id)+"?new_document_block=1" }
        format.json { render json: @document_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /document_blocks/1
  # PUT /document_blocks/1.json
  def update
    @document_block = DocumentBlock.find(params[:id])
    if params[:document_block_weight]
      weights = params[:document_block_weight].split("&").map{|s| s.gsub("element[]=", "") }
      @document_block.documents.each do |document|
        document.weight = weights.index(document.id.to_s)
        document.save
      end
    end
    respond_to do |format|
      if @document_block.update_attributes(params[:document_block])
        format.html {  redirect_to get_redirect_path, notice: 'Document block was successfully updated.' }
        format.json { head :ok }
      else
        flash[:error] = "Document block cannot be saved due to validation errors"
        format.html { redirect_to get_redirect_path  }
        format.json { render json: @document_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_blocks/1
  # DELETE /document_blocks/1.json
  def destroy
    @document_block = DocumentBlock.find(params[:id])
    @document_block.destroy

    respond_to do |format|
      flash[:notice] = "Document block <em>#{@document_block.title}</em> has been deleted.".html_safe
      format.html {redirect_to edit_portfolio_project_path(@document_block.project_id)+"?new_document_block=1"}
      format.json { head :ok }
    end
  end
  
  private
    
    def get_redirect_path
      edit_portfolio_project_path(@document_block.project)+"?document_block_id=#{@document_block.id}"
    end
end

app/helpers/document_blocks_helper.rb
module DocumentBlocksHelper
end

app/views/document_blocks/_document_block.html.erb
<p class="left bg3">
  <%= document_block.title %> 
</p>
<p class="right">
  <%= link_to "Edit", edit_document_block_path(document_block) %>
  <%= link_to "Remove", document_block_path(document_block), :method => :delete, :confirm => 'Are you sure you want to delete it?' %>
  <a href="#" class="drag_icon"></a>  
</p>

app/views/document_blocks/_form.html.erb
<%= form_for(@document_block) do |f| %>
 	<%= f.hidden_field :project_id %>
 	<%= hidden_field_tag 'document_block_weight', '' %>
 	
 	<p id="document_block_title_error" class="error hidden">* Title is required</p>
 	<p class="styled_text_field tb1 tb2-2 field">
 	 <%= f.text_field :title, :placeholder => 'Give your Attached Documents section a title (ex. References) ...' %>
 	</p>
 	<% if !@document_block.new_record?  %>
     <div class="add-buttons">
         <a href="<%= new_document_block_document_path(@document_block) %>" id="add_document" class="first fltlft iframe_fancy">+ Add a document</a>
         <p>*PDF, Word, PowerPoint, etc.</p>
     </div>  
     <div class="scrollbar">
       <div id="document_block_pane" class="scroll_pane"> 
       <ul id="document_element_list" class="organize-list">
         <% @document_block.documents.each  do |element| %>
            <li class="upload" id="element_<%= element.id %>"> 
               <%= render element %>
             </li>
         <% end %>
       </ul>
     </div> 
   <% end %>
   <p class="right actions" >

     <a id="save_document_btn" href="#" class="btn-1"><span><strong>
       <% if !@document_block.new_record?  %>
         Save document block
       <% else %>
         Create document block
       <% end %>
     </strong></span></a>
     <% if !@document_block.new_record?  %>
       <a id="save_document_block_btn" href="<%= new_document_block_path+"?project_id=#{@project.id}" %>" class="btn-2"><span><strong>Cancel</strong></span></a>
     <% end %>
   </p>
<% end %>

app/views/document_blocks/edit.html.erb
<h1>Editing document_block</h1>

<%= render 'form' %>

<%= link_to 'Show', @document_block %> |
<%= link_to 'Back', document_blocks_path %>

app/views/document_blocks/index.html.erb
<h1>Listing document_blocks</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @document_blocks.each do |document_block| %>
  <tr>
    <td><%= document_block.title %></td>
    <td><%= link_to 'Show', document_block %></td>
    <td><%= link_to 'Edit', edit_document_block_path(document_block) %></td>
    <td><%= link_to 'Destroy', document_block, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document block', new_document_block_path %>

app/views/document_blocks/new.html.erb
<h1>New document_block</h1>

<%= render 'form' %>

<%= link_to 'Back', document_blocks_path %>

app/views/document_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @document_block.title %>
</p>


<%= link_to 'Edit', edit_document_block_path(@document_block) %> |
<%= link_to 'Back', document_blocks_path %>