config/routes.rb
Stylejonction::Application.routes.draw do
  
  require 'subdomain'
  devise_for :users
  
  match "/users" => "users#index"
  
  constraints(Subdomain) do
    match '/' => 'portfolios#edit_layout'

    resource :portfolio, :except => [:destroy, :new] do
      member do
        get 'edit_layout'
        get 'edit_font'
        put 'publish'
      end
      resources :projects, :except => [:index]  do
        member do
          post 'invite'
        end
      end
    end
  end
  
  resources :custom_backgrounds, :only => [:edit, :update, :create] do
     member do
       post 'upload'
       get 'remove_upload'
     end
  end
  resources :predefined_backgrounds, :only => [:show]
  resources :patterns, :only => [:show]
  resources :invitations, :only => [:show]
  resources :fonts, :only => [:show]
  resources :images do
    member do
      post 'upload'
      match 'crop'
      match 'remove_upload'
    end
  end
  resources :text_blocks, :except => [:index]
  resources :galleries, :except => [:index] do 
    resources :videos
    resources :photos do 
      collection do
        post "upload" 
      end
    end
  end
  resources :document_blocks, :except => [:index] do 
    resources :documents
  end
  
  
  # This duplicates upload_image but doesn't need id
  match "/images/upload" => 'images#upload', :via => "post"

  #match "portfolio/:id" => "portfolios#show"
  match '#/:page' => 'pages#:page', :as => :page
  root :to => "pages#index"
end

app/models/text_block.rb
class TextBlock < Element
  
  belongs_to :project
  
  validates_presence_of :title, :project_id
  
end

app/controllers/text_blocks_controller.rb
class TextBlocksController < ApplicationController

  # GET /text_blocks/1
  # GET /text_blocks/1.json
  def show
    @text_block = TextBlock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_block }
    end
  end
  
  def new
    @text_block = TextBlock.new
    
    respond_to do |format|
      format.html{ redirect_to edit_portfolio_project_path(params[:project_id])+"?new_text_block=1" }
      format.json { render json: @text_block }
    end
  end
  
  
 

  # GET /text_blocks/1/edit
  def edit
    @text_block = TextBlock.find(params[:id])
    redirect_to get_redirect_path
  end

  # POST /text_blocks
  # POST /text_blocks.json
  def create
    @text_block = TextBlock.new(params[:text_block])
    respond_to do |format|
      if @text_block.save
        format.html { redirect_to get_redirect_path, notice: 'Writing was added successfully.' }
        format.json { render json: @text_block, status: :created, location: @text_block }
      else
        flash[:error] = "Writing cannot be created due to validation errors"
        format.html { redirect_to edit_portfolio_project_path(@text_block.project_id)+"?new_text_block=1" }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_blocks/1
  # PUT /text_blocks/1.json
  def update
    @text_block = TextBlock.find(params[:id])

    respond_to do |format|
      if @text_block.update_attributes(params[:text_block])
        format.html { redirect_to get_redirect_path, notice: 'Text block was successfully updated.' }
        format.json { head :ok }
      else
        flash[:error] = "Writing cannot be updated due to validation errors"
        format.html { redirect_to get_redirect_path  }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_blocks/1
  # DELETE /text_blocks/1.json
  def destroy
    @text_block = TextBlock.find(params[:id])
    @text_block.destroy

    respond_to do |format|
      flash[:notice] = "Writing <em>#{@text_block.title}</em> has been deleted.".html_safe
      format.html{ redirect_to edit_portfolio_project_path(@text_block.project_id)+"?new_text_block=1"}
      format.json { head :ok }
    end
  end
  
  private
    def get_redirect_path
      edit_portfolio_project_path(@text_block.project)+"?text_block_id=#{@text_block.id}"
    end
end

app/helpers/text_blocks_helper.rb
module TextBlocksHelper
end

app/views/text_blocks/_form.html.erb
<%= form_for(@text_block) do |f| %>
  <div class="hidden_fields">
  	<%= f.hidden_field :project_id %>
  </div>
  
  <p id="text_block_title_error" class="error hidden">* Title is required</p>
  <p class="styled_text_field tb1 field">
    <%= f.text_field :title, :placeholder => "Please insert a title ..." %>
  </p>
  <p class="styled_text_area field">
    <%= f.text_area :body, :rows => "5", :cols => "73", :placeholder => "Content goes here ..." %>
  </p>
  <p class="right actions" >
     <a id="save_text_block_btn" href="#" class="btn-1"><span><strong>
       <% if !@text_block.new_record?  %>
         Save writing
       <% else %>
         Create writing
       <% end %>
     </strong></span></a>
     <% if !@text_block.new_record?  %>
       <a id="cancel_text_block_btn" href="<%= new_text_block_path+"?project_id=#{@project.id}" %>" class="btn-2"><span><strong>Cancel</strong></span></a>
     <% end %>
   </p>

<% end %>

app/views/text_blocks/_text_block.html.erb
<p class="left bg1">
  <%= text_block.title %> 
</p>
<p class="right">
  <%= link_to "Edit", edit_text_block_path(text_block) %>
  <%= link_to "Remove", text_block_path(text_block), :method => :delete, :confirm => 'Are you sure you want to delete it?' %>
  <a href="#" class="drag_icon"></a>  
</p>

app/views/text_blocks/create.html.erb
<h1>TextBlocks#create</h1>
<p>Find me in app/views/text_blocks/create.html.erb</p>

app/views/text_blocks/destroy.html.erb
<h1>TextBlocks#destroy</h1>
<p>Find me in app/views/text_blocks/destroy.html.erb</p>

app/views/text_blocks/edit.html.erb
<h1>Editing text_block</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_block %> |
<%= link_to 'Back', text_blocks_path %>

app/views/text_blocks/index.html.erb
<h1>Listing text_blocks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @text_blocks.each do |text_block| %>
  <tr>
    <td><%= text_block.title %></td>
    <td><%= text_block.body %></td>
    <td><%= link_to 'Show', text_block %></td>
    <td><%= link_to 'Edit', edit_text_block_path(text_block) %></td>
    <td><%= link_to 'Destroy', text_block, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Text block', new_text_block_path %>

app/views/text_blocks/new.html.erb
<h1>New text_block</h1>

<%= render 'form' %>

<%= link_to 'Back', text_blocks_path %>

app/views/text_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @text_block.title %>
</p>

<p>
  <b>Body:</b>
  <%= @text_block.body %>
</p>


<%= link_to 'Edit', edit_text_block_path(@text_block) %> |
<%= link_to 'Back', text_blocks_path %>

app/views/text_blocks/update.html.erb
<h1>TextBlocks#update</h1>
<p>Find me in app/views/text_blocks/update.html.erb</p>