config/routes.rb
Stylejonction::Application.routes.draw do
  
  require 'subdomain'
  devise_for :users
  
  match "/users" => "users#index"
  
  constraints(Subdomain) do
    match '/' => 'portfolios#edit_layout'

    resource :portfolio, :except => [:destroy, :new] do
      member do
        get 'edit_layout'
        get 'edit_font'
        put 'publish'
      end
      resources :projects, :except => [:index]  do
        member do
          post 'invite'
        end
      end
    end
  end
  
  resources :custom_backgrounds, :only => [:edit, :update, :create] do
     member do
       post 'upload'
       get 'remove_upload'
     end
  end
  resources :predefined_backgrounds, :only => [:show]
  resources :patterns, :only => [:show]
  resources :invitations, :only => [:show]
  resources :fonts, :only => [:show]
  resources :images do
    member do
      post 'upload'
      match 'crop'
      match 'remove_upload'
    end
  end
  resources :text_blocks, :except => [:index]
  resources :galleries, :except => [:index] do 
    resources :videos
    resources :photos do 
      collection do
        post "upload" 
      end
    end
  end
  resources :document_blocks, :except => [:index] do 
    resources :documents
  end
  
  
  # This duplicates upload_image but doesn't need id
  match "/images/upload" => 'images#upload', :via => "post"

  #match "portfolio/:id" => "portfolios#show"
  match '#/:page' => 'pages#:page', :as => :page
  root :to => "pages#index"
end

app/models/video.rb
class Video < ActiveRecord::Base
   
   belongs_to :gallery
   
   validates_presence_of :weight, :gallery_id
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  layout "modal"
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_gallery
  before_filter :find_or_build_video
    
 
  # GET /videos/1
  # GET /videos/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    update_video
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    update_video
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
   
    @video.destroy

    respond_to do |format|
      format.html { redirect_to edit_gallery_path(@video.gallery) }
      format.json { head :ok }
    end
  end
  
  protected 
   def update_video
     respond_to do |format|
       if @video.update_attributes(params[:video])
         format.html { redirect_to edit_gallery_path(@video.gallery), notice: 'Video was successfully created.' }
         format.json { render json: @video, status: :created, location: @video }
       else
         format.html { render action: "new" }
         format.json { render json: @video.errors, status: :unprocessable_entity }
       end
     end
   end
   def find_gallery
      @gallery = Gallery.find(params[:gallery_id])
    end
    def find_or_build_video
      @video = params[:id] ? @gallery.videos.find(params[:id]) : @gallery.videos.new
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<section id="edit_video_section">
  <%= form_for [@gallery, @video] do |f| %>
  <div class="hidden_fields">
    <%= f.hidden_field :gallery_id %>
    <%= f.hidden_field :html %>
    <%= f.hidden_field :provider_name %>
    <%= f.hidden_field :thumbnail_height %>
    <%= f.hidden_field :thumbnail_width %>
    <%= f.hidden_field :thumbnail_url %>
    <%= f.hidden_field :width %>
    <%= f.hidden_field :height %>
  </div>
  <header>
  	  <h1 class="plus"><strong>Add</strong> a video to your gallery</h1>
  </header>
  
  <div class="content">
    <fieldset>
      <legend>Upload your video</legend>
      <p class="description">
        You must upload your video using one of the following video sharing websites
      </p>
      <div class="video-format">
        <%= image_tag "../images/video-format1.gif", :alt => 'Youtube' %>
        <%= image_tag "../images/video-format2.gif", :alt => 'vimeo' %>
        <%= image_tag "../images/video-format3.gif", :alt => 'blip.tv' %>
      </div>
      <div class="browse">
        <p class="tb3 styled_text_field left">
          <%= f.text_field :url, :placeholder => "copy & paste the video URL ...", :required => 'required_video'   %>
        </p>
        <a id="upload_video" href="#" class="btn-1"><span><strong>Link</strong></span></a>
    </div>
   </fieldset>
   <fieldset id="video_form" class=" <%= 'hidden' if @video.new_record? %>">
      <div id="video_preview">
        <%= image_tag @video.thumbnail_url, :width => 300 %>
      </div>
      <p class="ta1">
        <%= f.text_area :caption, :placeholder => "Video caption (optional) ...", :cols => 5, :row =>5 %>
      </p>
   </fieldset>
  </div>
  <footer id="video_actions" class="<%= 'hidden' if @video.new_record? %>">
    <a href="#" class="btn-1" id="save_video" ><span><strong>Save</span></strong></a>
    <a href="#" class="btn-2" id="cancel_video" ><span><strong>Cancel</span></strong></a>
  </footer>
  <% end %>
</section>

app/views/videos/_video.html.erb
<div class="element">
  <%= image_tag video.thumbnail_url, :width => 85,  :height => (video.thumbnail_height * 85 / video.thumbnail_width) %>
</div>
<p>
Uploaded video
</p>
<p class="fltrt">
  <%= link_to "Edit", edit_gallery_video_path(:id => video.id, :gallery_id => video.gallery_id), :class => 'edit_gallery_video' %>
  <%= link_to "Remove", gallery_video_path(:id => video.id, :gallery_id => video.gallery_id), :method => :delete, :confirm => 'Are you sure you want to delete this video?' %>
  <a href="#" class="drag_icon"></a>
</p>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>Caption</th>
    <th>Url</th>
    <th>Gallery</th>
    <th>Weight</th>
    <th>Provider name</th>
    <th>Thumbnail width</th>
    <th>Thumbnail height</th>
    <th>Thumbnail url</th>
    <th>Html</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.caption %></td>
    <td><%= video.url %></td>
    <td><%= video.gallery_id %></td>
    <td><%= video.weight %></td>
    <td><%= video.provider_name %></td>
    <td><%= video.thumbnail_width %></td>
    <td><%= video.thumbnail_height %></td>
    <td><%= video.thumbnail_url %></td>
    <td><%= video.html %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @video.caption %>
</p>

<p>
  <b>Url:</b>
  <%= @video.url %>
</p>

<p>
  <b>Gallery:</b>
  <%= @video.gallery_id %>
</p>

<p>
  <b>Weight:</b>
  <%= @video.weight %>
</p>

<p>
  <b>Provider name:</b>
  <%= @video.provider_name %>
</p>

<p>
  <b>Thumbnail width:</b>
  <%= @video.thumbnail_width %>
</p>

<p>
  <b>Thumbnail height:</b>
  <%= @video.thumbnail_height %>
</p>

<p>
  <b>Thumbnail url:</b>
  <%= @video.thumbnail_url %>
</p>

<p>
  <b>Html:</b>
  <%= @video.html %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>