config/routes.rb
Stylejonction::Application.routes.draw do
  
  require 'subdomain'
  devise_for :users
  
  match "/users" => "users#index"
  
  constraints(Subdomain) do
    match '/' => 'portfolios#edit_layout'

    resource :portfolio, :except => [:destroy, :new] do
      member do
        get 'edit_layout'
        get 'edit_font'
        put 'publish'
      end
      resources :projects, :except => [:index]  do
        member do
          post 'invite'
        end
      end
    end
  end
  
  resources :custom_backgrounds, :only => [:edit, :update, :create] do
     member do
       post 'upload'
       get 'remove_upload'
     end
  end
  resources :predefined_backgrounds, :only => [:show]
  resources :patterns, :only => [:show]
  resources :invitations, :only => [:show]
  resources :fonts, :only => [:show]
  resources :images do
    member do
      post 'upload'
      match 'crop'
      match 'remove_upload'
    end
  end
  resources :text_blocks, :except => [:index]
  resources :galleries, :except => [:index] do 
    resources :videos
    resources :photos do 
      collection do
        post "upload" 
      end
    end
  end
  resources :document_blocks, :except => [:index] do 
    resources :documents
  end
  
  
  # This duplicates upload_image but doesn't need id
  match "/images/upload" => 'images#upload', :via => "post"

  #match "portfolio/:id" => "portfolios#show"
  match '#/:page' => 'pages#:page', :as => :page
  root :to => "pages#index"
end

app/models/document.rb
class Document < ActiveRecord::Base
  
  belongs_to :document_block
  
  mount_uploader :file, DocumentUploader
  
  validates_presence_of :caption
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  
  layout "modal"
  
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_document_block
  before_filter :find_or_build_document
 
 

  # GET /documents/1
  # GET /documents/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
   respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
   
  end

  # POST /documents
  # POST /documents.json
  def create
    respond_to do |format|
      if @document.save
        format.html { redirect_to edit_document_block_path(@document.document_block), notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
   

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to edit_document_block_path(@document.document_block), notice: 'Document was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    
    @document.destroy
    respond_to do |format|
      format.html { redirect_to edit_document_block_path(@document.document_block) }
      format.json { head :ok }
    end
  end
  
  protected 
    def find_document_block
        @document_block = DocumentBlock.find(params[:document_block_id])
    end
    def find_or_build_document
        @document = params[:id] ? @document_block.documents.find(params[:id]) : @document_block.documents.build(params[:document])
    end
    
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div class="left element">
   <%= link_to document.caption, document.file.url %>
  
</div>
<p class="right fltrt">
    <%= link_to "Edit", 
                edit_document_block_document_path(:id => document.id, :document_block_id => document.document_block_id), 
                :class=> 'edit_document' %>
    <%= link_to "Remove", document_block_document_path(:id => document.id, :document_block_id => document.document_block_id),
                :method => :delete, 
                :confirm => 'Are you sure you want to delete this document?' %>
    <a href="#" class="drag_icon"></a>
</p>

app/views/documents/_form.html.erb
<section id="edit_document_section" class="edit_document_section">
  <%= form_for([@document_block, @document]) do |f| %>
    <div class="hidden_forms">
    </div>
    <header>
    	<h1 class="plus"><strong>Add</strong> a document</h1>
    </header>
    
    <section class="upload_document_section">
     <p class="description">
        <strong>Upload a document</strong>
        <br>
        <em>You can upload almost any type of document, including: <br>Word, Pdf, PowerPoint, Excel and more.</em>
     </p>
     <p id="document_extension_error" class="error hidden">* Type of document is not accepted.</p>
     <div class="browse">
      <p class="browse-but no-margin">
        <label class="cabinet">
        
          <%= f.file_field :file, :class => "file multi"  %>
        </label>
      </p>
      <a href="#" class="btn-1">
        <span><strong>Upload</strong></span>
      </a>
     </div>
     <p id="document_caption_error" class="error hidden">* Caption is required</p>
     <p class="ta1">
        <%= f.text_area :caption, :placeholder => "Document caption...", :cols => 5, :row => 5 %>
     </p>
     <footer>
        <a href="#" class="btn-1" id="save_document" ><span><strong>Save</span></strong></a>
        <a href="#" class="btn-2" id="cancel_document" ><span><strong>Cancel</span></strong></a>
     </footer>
  </section>
<% end %>

app/views/documents/edit.html.erb
<%= render 'form' %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th>Title</th>
    <th>File</th>
    <th>Content type</th>
    <th>Filesize</th>
    <th>Document block</th>
    <th>Weight</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.title %></td>
    <td><%= document.file %></td>
    <td><%= document.content_type %></td>
    <td><%= document.filesize %></td>
    <td><%= document.document_block_id %></td>
    <td><%= document.weight %></td>
    <td><%= link_to 'Show', document %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Destroy', document, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<%= render 'form' %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @document.title %>
</p>

<p>
  <b>File:</b>
  <%= @document.file %>
</p>

<p>
  <b>Content type:</b>
  <%= @document.content_type %>
</p>

<p>
  <b>Filesize:</b>
  <%= @document.filesize %>
</p>

<p>
  <b>Document block:</b>
  <%= @document.document_block_id %>
</p>

<p>
  <b>Weight:</b>
  <%= @document.weight %>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>